debug: false
management.endpoints.web.exposure.include: "*"

logging:
  level:
    com.fastcampus.projectboard: debug
    org.springframework.web.servlet: debug # req, res log ? ??
    org.hibernate.type.descriptor.sql.BasicBinder: trace # mysql query parameter trace

spring:
  application:
    name: board
  datasource:
    url: jdbc:mysql://localhost:13306/board
    username: fastcampus
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    defer-datasource-initialization: true # test ? ??? ??? ??
    # open-in-view: false
    show-sql: true
    properties:
      hibernate.format_sql: true # sql ? ???
      hibernate.default_batch_fetch_size: 100 # ?? ??? ??
    hibernate:
      ddl-auto: create
  h2.console.enables: false
  sql.init.mode: always
  data.rest:
    base-path: /api
    detection-strategy: annotated
  thymeleaf3:
    decoupled-logic: true


---
spring:
  config.activate.on-profile: testdb
#  datasource:
#    url: jdbc:h2:mem:board;mode=mysql
#    driverClassName: org.h2.Driver
#  sql.init.mode: always
#  test.database.replace: none